"""M14 · 用户策略代码 → QuantBT 模板。

支持 dialect：
- pandas：直接 pandas/numpy 的 `predict()` 函数
- backtrader：识别 Strategy.next() 内容
- vnpy：识别 CtaTemplate.on_bar()
- qlib：识别 RecordTemp / handler 类

实际改写用 `ast.parse` + `ast.NodeTransformer`；当 dialect 不识别时退回到
"包成 QuantBT predict shim"。
"""

from __future__ import annotations

import ast
import textwrap
from dataclasses import dataclass
from typing import Literal


SupportedDialect = Literal["pandas", "backtrader", "vnpy", "qlib"]


@dataclass
class ReplicationReport:
    dialect: SupportedDialect
    target_code: str
    notes: list[str]


_TEMPLATE_HEADER = textwrap.dedent(
    """
    # Generated by QuantBT Agent · code_replicator
    # source dialect: {dialect}
    from __future__ import annotations

    import polars as pl

    def predict(panel: pl.DataFrame) -> pl.DataFrame:
        \"\"\"QuantBT 标准 predict：输入 panel(ts,symbol,...) 返回 (ts,symbol,score)。\"\"\"
    """
).strip("\n")


class CodeReplicator:
    def replicate(self, code: str, dialect: SupportedDialect = "pandas") -> ReplicationReport:
        try:
            tree = ast.parse(code)
        except SyntaxError as exc:
            raise ValueError(f"无法解析用户代码：{exc}") from exc
        if dialect == "pandas":
            return self._pandas(code, tree)
        if dialect == "backtrader":
            return self._backtrader(code, tree)
        if dialect == "vnpy":
            return self._vnpy(code, tree)
        if dialect == "qlib":
            return self._qlib(code, tree)
        raise ValueError(f"未知 dialect: {dialect}")

    def _pandas(self, code: str, tree: ast.Module) -> ReplicationReport:
        notes: list[str] = []
        target_fn = self._find_function(tree, ["predict", "signal", "alpha"])
        if target_fn:
            body = ast.unparse(target_fn)
            target_code = _TEMPLATE_HEADER.format(dialect="pandas") + "\n    " + body.replace("\n", "\n    ")
            notes.append(f"识别到现成函数 `{target_fn.name}`，直接嵌入。")
        else:
            target_code = _TEMPLATE_HEADER.format(dialect="pandas") + "\n    raise NotImplementedError('TODO: 在此粘贴你的 alpha 公式')"
            notes.append("未找到 predict/signal/alpha 函数；生成模板占位。")
        return ReplicationReport(dialect="pandas", target_code=target_code, notes=notes)

    def _backtrader(self, code: str, tree: ast.Module) -> ReplicationReport:
        notes: list[str] = ["backtrader 的 Strategy.next() 通常引用 self.data.close。"]
        next_fn = self._find_function(tree, ["next"])
        body = ast.unparse(next_fn) if next_fn else "# TODO: 提取 next() 主体"
        target = _TEMPLATE_HEADER.format(dialect="backtrader") + textwrap.dedent(
            f"""
            # ---- 原始 next() 主体（需要手工替换 self.data.close → panel['close']） ----
            \"\"\"
            {body}
            \"\"\"
            raise NotImplementedError('请补全 next() → polars 表达式映射')
            """
        )
        return ReplicationReport(dialect="backtrader", target_code=target, notes=notes)

    def _vnpy(self, code: str, tree: ast.Module) -> ReplicationReport:
        notes: list[str] = [
            "vnpy CtaTemplate.on_bar() 包含真实账户调用，本工具仅提取信号逻辑。",
            "禁止移植 vnpy 的下单语句（A股不接券商；加密走 BinanceVenue）。",
        ]
        on_bar = self._find_function(tree, ["on_bar"])
        body = ast.unparse(on_bar) if on_bar else "# TODO: 提取 on_bar() 主体"
        target = _TEMPLATE_HEADER.format(dialect="vnpy") + textwrap.dedent(
            f"""
            # ---- 原始 on_bar()（**去掉了** self.buy/self.sell 调用） ----
            \"\"\"
            {body}
            \"\"\"
            raise NotImplementedError('请提取信号逻辑；下单交给 QuantBT 的 ExecutionVenue')
            """
        )
        return ReplicationReport(dialect="vnpy", target_code=target, notes=notes)

    def _qlib(self, code: str, tree: ast.Module) -> ReplicationReport:
        notes = ["Qlib 的 RecordTemp / handler 类需要先拆出 features() 与 label()。"]
        handler = self._find_function(tree, ["features", "feature", "fit"])
        body = ast.unparse(handler) if handler else "# TODO: 拆 Qlib handler"
        target = _TEMPLATE_HEADER.format(dialect="qlib") + textwrap.dedent(
            f"""
            # ---- Qlib handler.features() 主体 ----
            \"\"\"
            {body}
            \"\"\"
            raise NotImplementedError('请把 Qlib handler features → QuantBT 表达式因子')
            """
        )
        return ReplicationReport(dialect="qlib", target_code=target, notes=notes)

    def _find_function(self, tree: ast.Module, names: list[str]) -> ast.FunctionDef | None:
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name in names:
                return node
        return None


__all__ = ["CodeReplicator", "ReplicationReport", "SupportedDialect"]
